/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashActivitiesRouteImport } from './routes/_dash.activities'
import { Route as DashAdminRouteImport } from './routes/_dash.admin'
import { Route as DashCropsRouteImport } from './routes/_dash.crops'
import { Route as DashDashboardRouteImport } from './routes/_dash.dashboard'
import { Route as DashFarmsRouteImport } from './routes/_dash.farms'
import { Route as DashFinanceRouteImport } from './routes/_dash.finance'
import { Route as DashInventoryRouteImport } from './routes/_dash.inventory'
import { Route as DashMarketRouteImport } from './routes/_dash.market'
import { Route as DashProfileRouteImport } from './routes/_dash.profile'
import { Route as DashPurchasesRouteImport } from './routes/_dash.purchases'
import { Route as DashSalesRouteImport } from './routes/_dash.sales'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashActivitiesRoute = DashActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => DashRoute,
} as any)
const DashAdminRoute = DashAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashRoute,
} as any)
const DashCropsRoute = DashCropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardRoute = DashDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashRoute,
} as any)
const DashFarmsRoute = DashFarmsRouteImport.update({
  id: '/farms',
  path: '/farms',
  getParentRoute: () => DashRoute,
} as any)
const DashFinanceRoute = DashFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => DashRoute,
} as any)
const DashInventoryRoute = DashInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DashRoute,
} as any)
const DashMarketRoute = DashMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => DashRoute,
} as any)
const DashProfileRoute = DashProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashRoute,
} as any)
const DashPurchasesRoute = DashPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => DashRoute,
} as any)
const DashSalesRoute = DashSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activities': typeof DashActivitiesRoute
  '/admin': typeof DashAdminRoute
  '/crops': typeof DashCropsRoute
  '/dashboard': typeof DashDashboardRoute
  '/farms': typeof DashFarmsRoute
  '/finance': typeof DashFinanceRoute
  '/inventory': typeof DashInventoryRoute
  '/market': typeof DashMarketRoute
  '/profile': typeof DashProfileRoute
  '/purchases': typeof DashPurchasesRoute
  '/sales': typeof DashSalesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activities': typeof DashActivitiesRoute
  '/admin': typeof DashAdminRoute
  '/crops': typeof DashCropsRoute
  '/dashboard': typeof DashDashboardRoute
  '/farms': typeof DashFarmsRoute
  '/finance': typeof DashFinanceRoute
  '/inventory': typeof DashInventoryRoute
  '/market': typeof DashMarketRoute
  '/profile': typeof DashProfileRoute
  '/purchases': typeof DashPurchasesRoute
  '/sales': typeof DashSalesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dash': typeof DashRouteWithChildren
  '/auth': typeof AuthRoute
  '/_dash/activities': typeof DashActivitiesRoute
  '/_dash/admin': typeof DashAdminRoute
  '/_dash/crops': typeof DashCropsRoute
  '/_dash/dashboard': typeof DashDashboardRoute
  '/_dash/farms': typeof DashFarmsRoute
  '/_dash/finance': typeof DashFinanceRoute
  '/_dash/inventory': typeof DashInventoryRoute
  '/_dash/market': typeof DashMarketRoute
  '/_dash/profile': typeof DashProfileRoute
  '/_dash/purchases': typeof DashPurchasesRoute
  '/_dash/sales': typeof DashSalesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activities'
    | '/admin'
    | '/crops'
    | '/dashboard'
    | '/farms'
    | '/finance'
    | '/inventory'
    | '/market'
    | '/profile'
    | '/purchases'
    | '/sales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activities'
    | '/admin'
    | '/crops'
    | '/dashboard'
    | '/farms'
    | '/finance'
    | '/inventory'
    | '/market'
    | '/profile'
    | '/purchases'
    | '/sales'
  id:
    | '__root__'
    | '/'
    | '/_dash'
    | '/auth'
    | '/_dash/activities'
    | '/_dash/admin'
    | '/_dash/crops'
    | '/_dash/dashboard'
    | '/_dash/farms'
    | '/_dash/finance'
    | '/_dash/inventory'
    | '/_dash/market'
    | '/_dash/profile'
    | '/_dash/purchases'
    | '/_dash/sales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/activities': {
      id: '/_dash/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof DashActivitiesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/admin': {
      id: '/_dash/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof DashAdminRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/crops': {
      id: '/_dash/crops'
      path: '/crops'
      fullPath: '/crops'
      preLoaderRoute: typeof DashCropsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard': {
      id: '/_dash/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashDashboardRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/farms': {
      id: '/_dash/farms'
      path: '/farms'
      fullPath: '/farms'
      preLoaderRoute: typeof DashFarmsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/finance': {
      id: '/_dash/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof DashFinanceRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/inventory': {
      id: '/_dash/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof DashInventoryRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/market': {
      id: '/_dash/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof DashMarketRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/profile': {
      id: '/_dash/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashProfileRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/purchases': {
      id: '/_dash/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof DashPurchasesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/sales': {
      id: '/_dash/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof DashSalesRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface DashRouteChildren {
  DashActivitiesRoute: typeof DashActivitiesRoute
  DashAdminRoute: typeof DashAdminRoute
  DashCropsRoute: typeof DashCropsRoute
  DashDashboardRoute: typeof DashDashboardRoute
  DashFarmsRoute: typeof DashFarmsRoute
  DashFinanceRoute: typeof DashFinanceRoute
  DashInventoryRoute: typeof DashInventoryRoute
  DashMarketRoute: typeof DashMarketRoute
  DashProfileRoute: typeof DashProfileRoute
  DashPurchasesRoute: typeof DashPurchasesRoute
  DashSalesRoute: typeof DashSalesRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashActivitiesRoute: DashActivitiesRoute,
  DashAdminRoute: DashAdminRoute,
  DashCropsRoute: DashCropsRoute,
  DashDashboardRoute: DashDashboardRoute,
  DashFarmsRoute: DashFarmsRoute,
  DashFinanceRoute: DashFinanceRoute,
  DashInventoryRoute: DashInventoryRoute,
  DashMarketRoute: DashMarketRoute,
  DashProfileRoute: DashProfileRoute,
  DashPurchasesRoute: DashPurchasesRoute,
  DashSalesRoute: DashSalesRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
